blog/urls.py
from django.urls import path, re_path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog_index',views.blog_index.as_view(),name='blog_index'),

    re_path(r'^about/$',views.AboutView.as_view(),name='about'),

    re_path('r^postList/$',views.PostListView.as_view(),name='post_list'),
    re_path('r^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    re_path('r^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    re_path('r^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    re_path('r^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    re_path('r^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),

    re_path('r^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),

    re_path('r^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),

    re_path('r^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    re_path('r^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),

]

main_page/urls.py
from django.urls import path
from main_page import views
from data_viz import views as data_viz_views

app_name = 'main_page'

urlpatterns = [
    path('index',views.index,name='index'),
    path('data_viz_index',data_viz_views.data_viz_index,name='data_viz_index'),
]

psql_db/urls.py
from django.urls import path, re_path, include
from psql_db import views

app_name = 'psql_db'

urlpatterns = [
    path('psql_index',views.psql_index.as_view(),name='psql_index'),

    re_path(r'^listSchool/$', views.SchoolListView.as_view(), name='listSchool'),
    re_path(r'^listSchool/(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detailSchool'),
    re_path(r'^createSchool/$', views.SchoolCreateView.as_view(), name='createSchool'),
    re_path(r'^updateSchool/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='updateSchool'),
    re_path(r'^deleteSchool/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='deleteSchool'),

    re_path(r'^listStudent/$', views.StudentListView.as_view(), name='listStudent'),
    re_path(r'^listStudent/(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detailStudent'),
    re_path(r'^createStudent/$', views.StudentCreateView.as_view(), name='createStudent'),
    re_path(r'^updateStudent/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='updateStudent'),
    re_path(r'^deleteStudent/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='deleteStudent'),

    path('tech_dets',views.tech_dets.as_view(),name='tech_dets'),

]

website/urls.py
from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, re_path, include
from main_page import views
from blog import views as blogViews

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('data_viz/',include('data_viz.urls')),
    path('main_page/',include('main_page.urls')),
    path('education/',include('education.urls')),
    path('about_me/',include('about_me.urls')),
    path('psql_db/',include('psql_db.urls')),

    path('blog/',include('blog.urls')),


    #re_path('accounts/login/$',blogViews.login,name='login'),
    #re_path('accounts/logout/$',blogViews.logout,name='logout',kwargs={'next_page':'/'}),



]

psql_db/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 128)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return(self.name)

    def get_absolute_url(self):
        return reverse("psql_db:detailSchool", kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length = 128)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students', blank=True,null=True,on_delete=models.SET_NULL)

    def __str__(self):
        return(self.name)

    def get_absolute_url(self):
        return reverse("psql_db:detailStudent", kwargs={'pk':self.pk})

psql_db/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                    ListView, DetailView,
                                    CreateView, UpdateView, DeleteView)
from . import models

class psql_index(TemplateView):
    template_name = 'psql_db/index.html'

class tech_dets(TemplateView):
    template_name = 'psql_db/tech_dets.html'
#--------------------------------------------------------
# School Views
class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'psql_db/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal', 'location')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("psql_db:listSchool")

#----------------------------------------------------#
#Student Views

class StudentListView(ListView):
    context_object_name = 'students'
    model = models.Student

class StudentDetailView(DetailView):
    context_object_name = 'student_detail'
    model = models.Student
    template_name = 'psql_db/student_detail.html'

class StudentCreateView(CreateView):
    fields = ('name','age', 'school')
    model = models.Student

class StudentUpdateView(UpdateView):
    fields = ('name','age', 'school')
    model = models.Student

class StudentDeleteView(DeleteView):
    model = models.Student
    success_url = reverse_lazy("psql_db:listStudent")

psql_db/templates/psql_db/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dave-Krieger</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static "main_page/css/style.css" %}"/>

  </head>
  <body>

    <!-- Navbar content -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'main_page:index' %}">Main_Page</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link text-white" href="{% url 'psql_db:psql_index' %}">MVC PSQL Home</a>

            <div class="dropdown show">
              <a class="nav-item nav-link text-white dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                School Views
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'psql_db:listSchool' %}">List of Schools</a>
                <a class="dropdown-item" href="{% url 'psql_db:createSchool' %}">Create a School</a>
              </div>
            </div>

            <div class="dropdown show">
              <a class="nav-item nav-link text-white dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Student Views
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'psql_db:listStudent' %}">List of Students</a>
                <a class="dropdown-item" href="{% url 'psql_db:createStudent' %}">Create a Student</a>
              </div>
            </div>

            <a class="nav-item nav-link text-grey" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>

            <a class="nav-item nav-link text-white" href="{% url 'psql_db:tech_dets' %}">Technical_Details+Scrumboard <span class="sr-only">(current)</span></a>

        </div>
      </div>
    </nav>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

psql_db/templates/psql_db/index.html
{% extends "psql_db/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>Web Development Concepts Portfolio</center></h1>
    <h3><center>A basic program & seires of webpages designed to demonstrate some fundamental web development skills:</center></h3>
    <p></p>
    <div class="row">
      <div class="col-sm-6">
        <ul>
          <li>MVC</li>
          <li>PostgreSQL</li>
        </ul>
        </div>
      <div class="col-sm-6">
        <ul>
          <li>CRUD</li>
          <li>Deployment of DB on remote host</li>
        </ul>
      </div>
    </div>


    <p></p>
    <h5 class="text-center">Table of Contents</h5>

    <div class="list-group">

      <a href="{% url 'psql_db:listSchool' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">School Views</h5>
        </div>
        <p class="mb-1">Dropdown menu bar that lets users:</p>
        <ul>
          <li>List of Schools: Displays a list of all the current schools in the database</li>
          <li>Create a School: Allows users to create a new school to add to the database</li>
        </ul>
        <small class="text-muted">Portfolio</small>
      </a>

      <a href="{% url 'psql_db:listStudent' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Student Views</h5>
        </div>
        <p class="mb-1">Dropdown menu bar that lets users:</p>
        <ul>
          <li>List of Students: Displays a list of all the current student in the database</li>
          <li>Create a Student: Allows users to create a new student to add to the database</li>
        </ul>
        <small class="text-muted">Portfolio</small>
      </a>

      <a href="{% url 'psql_db:tech_dets' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Technical_Details+Scrumboard</h5>
        </div>
        <p class="mb-1">A brief description how the 'MVC w/ PSQL' webpages were developed and provides a psuedo-scrumboard for my plans</p>
        <small class="text-muted">Misc</small>
      </a>
    </div>
    <p></p>
  </div>
</div>


{% endblock %}

psql_db/templates/psql_db/school_confirm_delete.html
{% extends "psql_db/basic_app_base.html" %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>DELETE SCHOOL: {{school.name}}?</h1>
    <form method="post">
      {%csrf_token%}
      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'psql_db:detail' pk=school.pk %}"> Cancel</a>
    </form>
  </div>

</div>
<h1>Delete {{school.name}}</h1>



{% endblock %}

psql_db/templates/psql_db/school_detail.html
{% extends 'psql_db/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to the school details page.</h1>
  <hr style="width: 100%; color: black; height: 8px; background-color:black;" />

  <p></p>
  <h3>School details:</h3>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>

  <div class="btn-group" role="group" aria-label="Basic example">
    <p><a class='btn btn-warning mr-5' href="{% url 'psql_db:updateSchool' pk=school_detail.pk %}">Update</a></p>
    <p><a class='btn btn-danger mr-5' href="{% url 'psql_db:deleteSchool' pk=school_detail.pk %}">Delete</a></p>
  </div>


  <hr style="width: 100%; color: black; height: 8px; background-color:black;" />

  <h3>Students:</h3>
  <p></p>
  {% for student in school_detail.students.all %}
    <p>Student Name: {{student.name}}</p>
    <p>Student Age: {{student.age}}</p>
    <p>School Name: {{school_detail.name}}</p>
    <p>School Location: {{school_detail.location}}</p>
    <hr style="width: 100%; color: black; height: 1px; background-color:black;" />

  {% endfor %}

</div>

{% endblock %}

psql_db/templates/psql_db/school_form.html
{% extends "psql_db/basic_app_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" class="btn btn-primary" name="" value="Submit">

  </form>
</div>

{% endblock %}

psql_db/templates/psql_db/school_list.html
{% extends "psql_db/base.html" %}

{% block body_block %}

<h1>List of all the schools</h1>
  <ol>
    {% for school in schools %}
      <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock %}

psql_db/templates/psql_db/student_confirm_delete.html
{% extends "psql_db/base.html" %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>DELETE STUDENT: {{student.name}}?</h1>
    <form method="post">
      {%csrf_token%}
      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'psql_db:listStudent' pk=student.pk %}"> Cancel</a>
    </form>
  </div>

</div>
<h1>Delete {{student.name}}</h1>

{% endblock %}

psql_db/templates/psql_db/student_detail.html
{% extends 'psql_db/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to the student details page.</h1>
  <hr style="width: 100%; color: black; height: 8px; background-color:black;" />

  <p></p>
  <h3>Student details:</h3>
  <p>Name: {{student_detail.name}}</p>
  <p>Age: {{student_detail.age}}</p>
  <p>School: {{student_detail.school}}</p>

  <div class="btn-group" role="group" aria-label="Basic example">
    <p><a class='btn btn-warning mr-5' href="{% url 'psql_db:updateStudent' pk=student_detail.pk %}">Update</a></p>
    <p><a class='btn btn-danger mr-5' href="{% url 'psql_db:deleteStudent' pk=student_detail.pk %}">Delete</a></p>
  </div>

</div>

{% endblock %}

psql_db/templates/psql_db/student_form.html
{% extends "psql_db/base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create Student
  {% else %}
  Update Student
  {% endif %}
</h1>

<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" class="btn btn-primary" name="" value="Submit">

  </form>
</div>

{% endblock %}

psql_db/templates/psql_db/student_list.html
{% extends "psql_db/base.html" %}

{% block body_block %}

<h1>List of all the students</h1>
  <ol>
    {% for student in students %}
      <h2><li><a href="{{student.id}}">{{student.name}}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock %}

psql_db/templates/psql_db/tech_dets.html
{% extends "psql_db/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">'
    <h3 class="text-center">Technical_Details</h3>
    <p style="text-indent: 40px">These series of webpages run on the Django frameworks using <strong><i>class based views</i></strong>. It is designed as its own app, 'psql_db'. This was originally a lesson in writing class bassed views for django from the course: <a href="https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp/">here</a>, but I have since expanded upon it. Currently, I hope to add a geo-coordinate web-api so that I can assign students to closest schools.</p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h3 class="text-center"> SCRUMBOARD </h3>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />

    <h5>Not Started</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Create webpage dedicated to explaining the program</li>
      <li><i class="fa-li fa fa-times"></i>Fix alignment of forms: create/update</li>
    </ul>

    <p></p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>In Progress</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-spinner fa-spin"></i>N/A</li>
    </ul>


    <p></p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>Future development goals - "Reach"</h5>

    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Add web-api to this series. Maybe geo-coords</li>
      <ul class="fa-ul">
        <li><i class="fa-li fa fa-times"></i>Generate a few schools across US</li>
        <li><i class="fa-li fa fa-times"></i>Generate many students w/ specific adresses</li>
        <li><i class="fa-li fa fa-times"></i>Use web api to determine dist from student to school</li>
        <li><i class="fa-li fa fa-times"></i>Assign students to closest school</li>
      </ul>
    </ul>

    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Create more models... to play around for later </li>
      <ul class="fa-ul">
        <li><i class="fa-li fa fa-times"></i>Family</li>
        <li><i class="fa-li fa fa-times"></i>Food</li>
        <li><i class="fa-li fa fa-times"></i>Hobbies</li>
      </ul>
    </ul>

</div>
</div>


<!-- /Home -->

{% endblock %}