blog/urls.py
from django.urls import path, re_path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog_index',views.blog_index.as_view(),name='blog_index'),

    re_path(r'^about/$',views.AboutView.as_view(),name='about'),

    re_path('r^postList/$',views.PostListView.as_view(),name='post_list'),
    re_path('r^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    re_path('r^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    re_path('r^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    re_path('r^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    re_path('r^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),

    re_path('r^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),

    re_path('r^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),

    re_path('r^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    re_path('r^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),

]

data_viz/urls.py
from django.urls import path
from data_viz import views

app_name = 'data_viz'

urlpatterns = [
    path('data_viz_index',views.data_viz_index,name='data_viz_index'),
    path('temperature',views.temperature,name='temperature'),
    path('co2',views.co2,name='co2'),
    path('sdp',views.sdp,name='sdp'),
    path('data_wrangle',views.data_wrangle,name='data_wrangle'),
    path('tech_dets',views.tech_dets,name='tech_dets'),

]

website/urls.py
from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, re_path, include
from main_page import views
from blog import views as blogViews

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('data_viz/',include('data_viz.urls')),
    path('main_page/',include('main_page.urls')),
    path('education/',include('education.urls')),
    path('about_me/',include('about_me.urls')),
    path('psql_db/',include('psql_db.urls')),

    path('blog/',include('blog.urls')),


    #re_path('accounts/login/$',blogViews.login,name='login'),
    #re_path('accounts/logout/$',blogViews.logout,name='logout',kwargs={'next_page':'/'}),



]

data_viz/views.py
from django.shortcuts import render
# Create your views here.
def data_viz_index(request):
    return render(request, 'data_viz/index.html')

def temperature(request):
    return render(request, 'data_viz/temperature.html')

def co2(request):
    return render(request, 'data_viz/co2.html')

def data_wrangle(request):
    return render(request, 'data_viz/data_wrangle.html')

def tech_dets(request):
    return render(request, 'data_viz/tech_dets.html')

def sdp(request):
    return render(request, 'data_viz/senior-design.html')

data_viz/templates/data_viz/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dave-Krieger</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static "main_page/css/style.css" %}"/>

  </head>
  <body>
      <!-- Navbar content -->
      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">

        <a class="navbar-brand" href="{% url 'index' %}">Main_Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link text-white" href="{% url 'data_viz:data_viz_index' %}">Data Visualization Home</a>
            <a class="nav-item nav-link text-white" href="{% url 'data_viz:sdp' %}">Senior Design</a>
            <a class="nav-item nav-link text-white" href="{% url 'data_viz:temperature' %}">Temperature</a>
            <a class="nav-item nav-link text-white" href="{% url 'data_viz:co2' %}">Carbon Dioxide</a>
            <a class="nav-item nav-link text-white" href="{% url 'data_viz:data_wrangle' %}">Data Wrangling</a>
            <a class="nav-item nav-link text-white" href="{% url 'data_viz:tech_dets' %}">Technical_Details+Scrumboard</a>
          </div>
        </div>
      </nav>






    <div class="">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

data_viz/templates/data_viz/co2.html
{% extends "data_viz/base.html" %}
{% block body_block %}
{% load static %}



    <!-- Google font -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom stlylesheet -->

    <link rel="stylesheet" type="text/css" href="{% static "data_viz/css/co2ScatterPlot.css" %}">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static "data_viz/css/style.css" %}"/>

    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/queue.v1.min.js"></script>
    <script src="https://d3js.org/topojson.v1.min.js"></script>

    <script src="https://d3js.org/d3-color.v1.min.js"></script>
    <script src="https://d3js.org/d3-interpolate.v1.min.js"></script>
    <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>





    <script src="{% static "data_viz/js/core/d3-tip.js" %}" type="text/javascript"></script>

    <div id="slider"></div>

    <script src="{% static "data_viz/js/co2/co2ChoroInit.js" %}" type="text/javascript">     </script>
    <script src="{% static "data_viz/js/co2/co2ChoroSlider.js" %}" type="text/javascript">   </script>
    <script src="{% static "data_viz/js/co2/co2ChoroButtons.js" %}" type="text/javascript">  </script>
    <script src="{% static "data_viz/js/co2/co2Choro.js" %}" type="text/javascript">         </script>
    <script src="{% static "data_viz/js/co2/co2ChoroHelper.js" %}" type="text/javascript">   </script>



{% endblock %}

data_viz/templates/data_viz/data_wrangle.html
{% extends "data_viz/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">
    <h3><center>A page dedicated to various data-wrangling scripts I wrote for my senior design project team, Visualized Climate Change</center></h3>
    <p>I wrote a handful of python parsing scripts for my team. I did this because some individualswere being 'blocked' from developing their visualizations because they couldn't get their data formatted right</p>
    <p>These files don't have very good programming practices because I was in a huge RUSH to complete them. I also knew that once they were completed, we would likely never go back to re-use them. You've been warned.</p>

    <h5>This wrangling script converts multiple .tsv files to a single .json file. The rendered visual from the formatted dataset can be viewed <a href="https://climate-visuals.herokuapp.com/energy/energy.html" target="_blank">here</a>.</h5>

</div>


<div class="container">
  <div class="jumbotron ">
    <h1 class="text-center">Energy Sunburst I/O</h1>
    <!-- <p>This dataset was probably the hardest one I worked with. The raw input datafiles were 'dirty' tsv's split into twelve different categories. The output was a single .json file sorted by year -> country -> category : amount. It involved nested lists, string compares, and typecasting</p> -->

    <h3>Input</h3>
    <p>Twelve 'dirty' TSV files sorted by energy category. Two of which are very important, total energy consumption & total energy production, because they are used later to calculate net energy.</p>
    <img class="img-fluid" src="{% static 'data_viz/img/dir.png' %} " alt=""> </img>

    <p></p>
    <p>Each file was a 'dirty' tsv because they contained weird characters and unneccessary strings at the top of each file. I removed these issues with a small script not shown.</p>

    <img class="img-fluid" src="{% static 'data_viz/img/Input.png' %} " alt=""> </img>
    <p></p>
    <p></p>

    <h3>Output</h3>
    <p>A single .json file sorted by year -> country -> category : amount.</p>
    <img class="img-fluid" src="{% static 'data_viz/img/Output.png' %} " alt=""> </img>

  </div>
</div>

<div class="container">
  <div class="jumbotron ">
    <h1 class="text-center">Energy Sunburst Wrangle Code</h1>
    <!-- <p>This dataset was probably the hardest one I worked with. The raw input datafiles were 'dirty' tsv's split into twelve different categories. The output was a single .json file sorted by year -> country -> category : amount. It involved nested lists, string compares, and typecasting</p> -->

    <h3 class="">Start</h3>
    <div class="row">
      <div class="col-sm-6">
        <img class="img-fluid" src="{% static 'data_viz/img/start.png' %} " alt="">
      </div>

      <div class="col-sm-6"><p>Init and start section. I made use of a global var so I didn't have to keep passing it.</p>
        <p>The getyears() func generates a list of all the years: 1990-2018</p>
        <p>For each file within the system, read the file's data and store that the entire dictionary as list element in allList.</p>
        <p>Generate .json output file based on the data... we'll go more indepth in a bit.</p>
      </div>

    </div>
    <p></p>
    <h3 class="">readFiles()</h3>
    <div class="row">
      <div class="col-sm-6">
        <img class="img-fluid" src="{% static 'data_viz/img/first_func.png' %} " alt="">
      </div>

      <div class="col-sm-6">
        <p>Navigate to directory and create file name strings</p>
        <p>split each line based on their delimiter: tab or '\t'</p>
        <p>The first token is the country string. If this country has never been read before, create a new country by passing it as a new element to the global list: countryList</p>
        <p>Check bounds based on year span. If safe, then add each year's value to a temp list.</p>
        <p>Once completed, store the templist as a nested list within another temporary list called: thisFileList. </p>
        <p>Continue going line by line adding each line's data as tuple data to thisFileList.</p>
        <p>Finally, iterate through all the files adding 'thisFileList' as an index to 'allList'</p>
        <p></p>
      </div>

    </div>

    <p></p>
    <h3 class="">writeToFile</h3>
    <div class="row">
      <div class="col-sm-6">
        <img class="img-fluid" src="{% static 'data_viz/img/write_1.png' %} " alt="">
      </div>

      <div class="col-sm-6">
        <p>A few different obj's being passed:
        <ul>
          <li>outFileString: name of the output file</li>
          <li>yearList: list from 1990-2018</li>
          <li> countryList: list of every country that was read from the input files</li>
          <li>allList: list of each file's data</li>
        </ul>
        <p>Create the output file along with the first header information.</p>
        <p>Our data is first organized by year. Hence we iterate through the years as saved in yearList</p>
        <p>Time for some nested loops based on the nested list data, all iterating and indexing based on year! This is why using a list/array was nice. Instead of having to bind data to each year, I carefully saved each datapoint into the correct index which why we iterate from range(1,29).</p>
        <p>For every country that was read, go through the allList searching for two specfic datasets: energy production & consumption. Once found, find the net sum and save that as totalVal</p>
      </div>

    </div>

    <p></p>
    <div class="row">
      <div class="col-sm-6">
        <img class="img-fluid" src="{% static 'data_viz/img/write_2.png' %} " alt="">
      </div>

      <div class="col-sm-6">
        <p>Now write the data to the file in a .json format</p>
        <p>Write the country name and associated net energy amount. Create a newline and indent it. keep this indentation size while iterating through each file's data which is saved in allList.</p>
        <p>Write the corresponding energy type name and the associated data amount.</p>
        <p>After each file is read and the correct data is written, check to see if we have written data for every country for THIS YEAR ONLY. If not last country, add a ',' if it is the last, don't add a ','</p>
        <p>Some more formatting stuff checking the year and seeing if we need to add a ',' or not</p>
      </div>

    </div>

    <p></p>
    <h3 class="">Finished Product</h3>
    <p>So 19,000 lines later we reach the nested data section of energy consumption for 2018. Having nested data like this exponentially increases the file size compared to its original smaller .tsv form. However, certain applications may require a .json form such as this one. It's helpful because it enables other api's/parsers to easily interpret the data as a key:value pair with parent & child node relationships.</p>
      <img class="img-fluid" src="{% static 'data_viz/img/Output.png' %} " alt="">
  </div>
</div>



<!-- /Home -->
<div class="container">
  <div class="jumbotron">
    <p></p>
    <h1>Final Words</h1>
    <p>This dataset was probably the hardest one I worked with. The requirements of tracking all the data, storing it, and iterating over it was not a trivial task (for me at least...). If you want to explore more of my parsing code, feel free to explore: <a href="https://github.com/Dave-Krieger/Krieger-Dave-Portfolio/tree/master/visualizing-climate-change/dataSets" target="_blank">here</a> The parsing files are usually called 'convert.py'.</p>

  </div>
</div>
{% endblock %}

data_viz/templates/data_viz/index.html
{% extends "data_viz/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>Data Visualizations Home </center></h1>
    <h4><center>A portfolio of the work I accomplished for my computer science senior design project</center></h4>
    <p></p>
    <h5 class="text-center">Table of Contents</h5>

    <div class="list-group">
      <a href="{% url 'data_viz:sdp' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Senior Design</h5>
        </div>
        <p class="mb-1">Explains everything about my senior design project and what I took away from it.</p>
        <small class="text-muted">Education/Portfolio</small>
      </a>

      <a href="{% url 'data_viz:temperature' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Temperature</h5>
        </div>
        <p class="mb-1">Interactive temperature choropleth</p>
        <ul class="fa-ul">
          <li><i class="fa-li fa fa-spinner fa-spin"></i>Coming Soon: Supplemental Video!</li>
        </ul>
        <small class="text-muted">Portfolio/Communication</small>
      </a>

      <a href="{% url 'data_viz:co2' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Carbon Dioxide</h5>
        </div>
        <p class="mb-1">Interactive carbon dioxide choropleth"</p>
        <ul class="fa-ul">
          <li><i class="fa-li fa fa-spinner fa-spin"></i>Coming Soon: Supplemental Video!</li>
        </ul>
        <small class="text-muted">Portfolio/Communication</small>
      </a>

      <a href="{% url 'data_viz:data_wrangle' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Data Wrangling </h5>
        </div>
        <p class="mb-1">A step-by-step breakdown of one of the python wrangling scripts I wrote for my team.</p>
        <small class="text-muted">Portfolio</small>
      </a>

      <a href="{% url 'data_viz:tech_dets' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Technical_Details & Scrumboard</h5>
        </div>
        <p class="mb-1">A brief description how the data_viz webpages were developed and provides a psuedo-scrumboard</p>
        <small class="text-muted">Technical</small>
      </a>
    </div>

  </div>
</div>

<!-- /Home -->

{% endblock %}

data_viz/templates/data_viz/senior-design.html
{% extends "data_viz/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">'

    <h1 class="text-center" >Senior Design Project</h1>

    <h5>What is the senior design project</h5>
    <p style="text-indent: 40px">Every CS/EE student is required to complete a year long 'capstone' project in order to graduate. During this time, students work together in teams of 4-6 members with the support of corporate or factilty sponsorship. The first quarter is dedicated to learning software development practices such as the agile methodology, clean coding, and version control while the second and third quarter has students apply these principles based on the sponsor's project.</p>

    <h5>My project</h5>
    <p style="text-indent: 40px">My capstone project, visualizing climate change, was sponsored through the capstone course instructor, Richard Julig. I led a team of three other students as scrum master to develop the data visualizations. While our focus was to develop and investigate unique data visualizations for education purposes, I felt we never really accomplished education aspect. That said, I believe we did succeed in creating valuable visualizations.</p>

    <h1 class="text-center"><a href="https://climate-visuals.herokuapp.com/" target="_blank">Capstone Website</a></h1>



</div>
</div>


<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">The Development Experience</h1>

    <h3>Agile methodology</h3>
    <div class="row">
      <div class="col-sm-6">
        <h5>Pros</h5>
        <ul class="fa-ul">

          <li><i class="fa-li fa fa-plus"></i> Adaptive to unforseen obstacles</li>
          <p></p>
          <ul>
            <li> We didn't realize what we were getting ourselves into when learning D3. We chronically underestimated the required hours to develop visualization components. Having the agile methodology allowed us backlog and adjust our goals as needed.</li>
          </ul>

          <p></p>
          <li><i class="fa-li fa fa-plus"></i>Valuable 'toolset'</li>
          <p></p>
          <ul>
            <li>Agile systems provide the tools needed to thrive: sprints plans/reviews, scrumboard, burn-up chart. These tools helped keep my team from completely falling apart by holding people accountable for their work.</li>
          </ul>

        </ul>
      </div>

      <div class="col-sm-6">
        <p></p>

        <h5>Cons</h5>
        <ul class="fa-ul">

          <li><i class="fa-li fa fa-times"></i>Backlogging yielded team laziness</li>
          <p></p>
          <ul>
            <li>Because it was so easy to backlog work, I believe my teammates started to get lazy and not do their work. They oftensed said tasks were 'harder than expected' and then backlog the work which didn't get completeted...</li>
          </ul>

          <p></p>
          <li><i class="fa-li fa fa-times"></i>Difficult to plan expected hours per task</li>
          <p></p>
          <ul>
            <li>Scrum requires time estimates for task planning. However, because we were working with new technologies and had little support from our sponsor, it was difficult to know how long something would take. SCRUM planning + novel technologies was a mess.</li>
          </ul>

        </ul>
      </div>
    </div>


    <h3>Teamwork & Communication</h3>

    <h5>Slack communication</h5>
    <p>We used slack to communicate throughout our development. While it was a the technology itself did its job very well, I believe we failed to communicate regularly. The lack of communication started to slowly poison our team during the second quarter of development. It made people feel like others weren't doing work resulting in a feedback loop which slowed development significantl. I believe if there were more 'punishing' outcomes from failing to show up to meetings/completeting work, the development process would have gone much different.



  </div>
</div>




<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">Personal Contributions</h1>
<p>Below are my contributions to the senior design project. I have tried to provided links per listed item, but unfortunately some of the work is broken up across multiple files.</p>
<ul>
  <li>Writing python parsing scripts to format datasets.</li>
  <ul>
    <li>Step-by-step discussion of one of the parsing scripts I wrote: <a href="http://127.0.0.1:8000/data_viz/data_wrangle" target="_blank">Here</a></li>
    <li>Code: <a href="https://github.com/schan54/Data-Visualization/blob/master/dataSets/energy/createAllEnergy/totalConvert.py" target="_blank">Here</a></li>
  </ul>

  <li>Project directory management: <a href="https://github.com/schan54/Data-Visualization" target="_blank">Here</a></li>
  <li>Overhauled original barebone website to use free HTML/CSS template for front page & nav:</li>
  <ul>
    <li>I left the CSS to my teammates for their respective climate change pages for temperature, co2, energy, and sea level...</li>
  </ul>

  <li>Heroku integration and upkeep</li>
  <li>The choropleth visualization</li>
  <ul>
    <li>Choropleth: <a href="http://127.0.0.1:8000/data_viz/temperature" target="_blank">Here</a></li>
    <li>Code: <a href="https://github.com/schan54/Data-Visualization/tree/aa851bdf4b05567cc5d4d3ed6fdfbf8036860d5c/src/temperature" target="_blank">Here</a></li>
  </ul>

  <li>D3 specifc modules for re-use by teammates (NOT traditional HTML/CSS):</li>
  <ul>
    <li>Tooltips</li>
    <li>Button management: <a href="https://github.com/schan54/Data-Visualization/blob/master/src/temperature/tempChoroButtons.js" target="_blank">Here</a></li>
    <li>Input Text Box & Sanitization: <a href="https://github.com/schan54/Data-Visualization/blob/aa851bdf4b05567cc5d4d3ed6fdfbf8036860d5c/src/temperature/tempChoroButtons.js#L110" target="_blank">Here</a></li>
  </ul>

</ul>
</div>
</div>
<!-- /Home -->

{% endblock %}

data_viz/templates/data_viz/tech_dets.html
{% extends "data_viz/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">'
    <h3 class="text-center">Technical_Details</h3>
    <p>These series of webpages run on the Django frameworks using <strong><i>functional based views</i></strong>. It is designed as its own app, 'data_viz'. I had to do a massive overhaul converting the old capstone website visuals to work on the django setup. While I did get the job done, it was a bit of a hackjob. The CSS is off for the two visualization pages still...</p>

    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h3 class="text-center"> SCRUMBOARD </h3>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />

      <h5>Not Started</h5>
      <ul class="fa-ul">
        <li><i class="fa-li fa fa-times"></i>Complete landing page text</li>
        <li><i class="fa-li fa fa-times"></i>Add videos & text to choropleth sections</li>
        <li><i class="fa-li fa fa-times"></i>Add energy choropleth to website</li>
        <li><i class="fa-li fa fa-times"></i> Fix CSS for this series of webpages</li>
        <ul class="fa-ul">
          <li><i class="fa-li fa fa-times"></i>This was caused by the fact I imported the old CSS from my senior design class so the visuals would render correctly.</li>
        </ul>
      </ul>

      <p></p>
      <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
      <h5>In Progress</h5>
      <ul class="fa-ul">
        <li><i class="fa-li fa fa-spinner fa-spin"></i>N/A</li>
      </ul>

      <p></p>
      <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
      <h5>Future development goals - "reach"</h5>
      <ul class="fa-ul">
        <li><i class="fa-li fa fa-times"></i>Create webpage dedicated to a breakdown of how I wrote the choropleth visualizations</li>
      </ul>
</div>
</div>


<!-- /Home -->

{% endblock %}

data_viz/templates/data_viz/temperature.html
{% extends "data_viz/base.html" %}
{% block body_block %}

{% load static %}

    <!-- Google font -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom stlylesheet -->

    <link rel="stylesheet" type="text/css" href="{% static "data_viz/css/co2ScatterPlot.css" %}">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static "data_viz/css/style.css" %}"/>

    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/queue.v1.min.js"></script>
    <script src="https://d3js.org/topojson.v1.min.js"></script>

    <script src="https://d3js.org/d3-color.v1.min.js"></script>
    <script src="https://d3js.org/d3-interpolate.v1.min.js"></script>
    <script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>


    <script src="{% static "data_viz/js/core/d3-tip.js" %}" type="text/javascript"></script>

    <div id="slider"></div>
    <div id="choroInputBox"></div>

    <script src="{% static "data_viz/js/temperature/tempChoroInit.js" %}" type="text/javascript">     </script>
    <script src="{% static "data_viz/js/temperature/tempChoroSlider.js" %}" type="text/javascript">   </script>
    <script src="{% static "data_viz/js/temperature/tempChoroButtons.js" %}" type="text/javascript">  </script>
    <script src="{% static "data_viz/js/temperature/tempChoro.js" %}" type="text/javascript">         </script>
    <script src="{% static "data_viz/js/temperature/tempChoroHelper.js" %}" type="text/javascript">   </script>



{% endblock %}