about_me/urls.py
from django.urls import path
from about_me import views

app_name = 'about_me'

urlpatterns = [
    path('about_me_index',views.about_me_index,name='about_me_index'),
    path('hobbies',views.hobbies,name='hobbies'),
    path('leader',views.leader,name='leader'),
    path('programming',views.programming,name='programming'),
    path('tech_dets',views.tech_dets,name='tech_dets'),

]

blog/urls.py
from django.urls import path, re_path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog_index',views.blog_index.as_view(),name='blog_index'),

    re_path(r'^about/$',views.AboutView.as_view(),name='about'),

    re_path('r^postList/$',views.PostListView.as_view(),name='post_list'),
    re_path('r^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    re_path('r^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    re_path('r^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    re_path('r^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    re_path('r^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),

    re_path('r^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),

    re_path('r^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),

    re_path('r^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    re_path('r^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),

]

website/urls.py
from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, re_path, include
from main_page import views
from blog import views as blogViews

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('data_viz/',include('data_viz.urls')),
    path('main_page/',include('main_page.urls')),
    path('education/',include('education.urls')),
    path('about_me/',include('about_me.urls')),
    path('psql_db/',include('psql_db.urls')),

    path('blog/',include('blog.urls')),


    #re_path('accounts/login/$',blogViews.login,name='login'),
    #re_path('accounts/logout/$',blogViews.logout,name='logout',kwargs={'next_page':'/'}),



]

about_me/views.py
from django.shortcuts import render
# Create your views here.
def about_me_index(request):
    return render(request, 'about_me/index.html')

def hobbies(request):
    return render(request, 'about_me/hobbies.html')

def programming(request):
    return render(request, 'about_me/programming.html')

def leader(request):
    return render(request, 'about_me/leader.html')

def tech_dets(request):
    return render(request, 'about_me/tech_dets.html')

about_me/templates/about_me/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dave-Krieger</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static "main_page/css/style.css" %}"/>

  </head>
  <body>
      <!-- Navbar content -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">Main_Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link text-white" href="{% url 'about_me:about_me_index' %}">About Me Home</a>
            <a class="nav-item nav-link text-white" href="{% url 'about_me:hobbies' %}">Hobbies</a>
            <a class="nav-item nav-link text-grey disabled" href="{% url 'about_me:programming' %}">Programming</a>
            <a class="nav-item nav-link text-grey disabled" href="{% url 'about_me:leader' %}">Leader</a>
            <a class="nav-item nav-link text-white" href="{% url 'about_me:tech_dets' %}">Technical_Details+Scrumboard</a>

          </div>
        </div>
      </nav>

    <div class="">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

about_me/templates/about_me/hobbies.html
{% extends "about_me/base.html" %}
{% load static %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>What do I do in my offtime?</center></h1>

    <p></p>
    <h5>Music</h5>
    <p>Playing music has been a critical component throught my whole life. Ever since elementary school, I have been playing an assorted range of woodwinds. Eventually my love of music expanded past just woodwinds which has brought me to my current journey on playing & learning the guitar. Finally, because I am not playing a woodwind, it has provided me the opportunity to work on my voice as well!  </p>

    <p></p>
    <h5>Video Games</h5>
    <p>Playing music has been a critical compenent throught my whole life. Ever since elementary school, I have been playing an assorted range of woodwinds. Eventually my love of music expanded past just woodwinds which has brought me to my current journey on playing & learning the guitar. Finally, because I am not playing a woodwind, it has provided me the opportunity to work on my voice as well!  </p>

    <!-- <dl class="row">

      <h5></h5>

        <dt class="col-sm-3">Music</dt>
        <dd class="col-sm-9">I grew up playing multiple woodwinds: saxophone, bassoon, clarinet, and flute. Currently, my musical ambitions lies mostly between the saxophone and guitar.</dd>

        <dt class="col-sm-3 text-truncate">Gaming</dt>
        <dd class="col-sm-9">I'm definately an avid gamer who plays a wide variety of games in my offtime. I used to engage in competitive gaming and even did some semi-pro tounrmanets in Overwatch.</dd>

        <dt class="col-sm-3">Hiking/Camping/Traveling</dt>
        <dd class="col-sm-9">My parents instilled a strong love for the outdoors & traveling which I hope to continue. I have traveled to dozens of countries and multiple continents, ask me about it!</dd>

        <dt class="col-sm-3">Cycling/Mountain Biking</dt>
        <dd class="col-sm-9">Ever since high school I rode my bike to school. I continued the tradition throughout college and would hopefully like to do the same wherever work takes me.</dd>
    </dl> -->


  </div>
</div>
<!--
<div class="container">
  <div class="jumbotron">'
    <h1><center>I also have a cat, Mira</center></h1>
    <p>I guess maybe not a hobby...? Either way, here's my cat who is a mix of mainecoon and long-hair. She loves boxes, playtime, and my mousepad. She also likes to make sure I don't sleep in too late and leave cups on the counter. I don't care, she's awesome!</p>
  </div>
</div> -->

{% endblock %}

about_me/templates/about_me/index.html
{% extends "about_me/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>About Me</center></h1>
    <h3><center>I am a 23 year old double-major graduade from University of Santa Cruz. I currently still live in Santa Cruz and am searching for a job.</center></h3>

    <p></p>
    <h5 class="text-center">Table of Contents</h5>

    <div class="list-group">

      <a href="{% url 'about_me:hobbies' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Hobbies</h5>
        </div>
        <p class="mb-1">Find out what I do in my spare time</p>
        <small class="text-muted">Personal</small>
      </a>

      <a href="{% url 'about_me:programming' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Programming</h5>
        </div>
        <p class="mb-1">Explore my current and past progamming habits and preferences</p>
        <small class="text-muted">Portfolio/Personal</small>
      </a>

      <a href="{% url 'about_me:leader' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Leadership Skills</h5>
        </div>
        <p class="mb-1">Learn about my experiences as a lifelong leader</p>
        <small class="text-muted">Communication/Portfolio/Personal</small>
      </a>

      <a href="{% url 'about_me:tech_dets' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Technical_Details+Scrumboard</h5>
        </div>
        <p class="mb-1">A brief description how the about_me webpages were developed and provides a psuedo-scrumboard for my plans</p>
        <small class="text-muted">Personality</small>
      </a>

    </div>
    <p></p>
  </div>
</div>


{% endblock %}

about_me/templates/about_me/leader.html
{% extends "about_me/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>Leader</center></h1>
    <h3><center>#In development</center></h3>

  </div>
</div>


{% endblock %}

about_me/templates/about_me/programming.html
{% extends "about_me/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>Programming</center></h1>
    <h3><center></center></h3>


  </div>
</div>


{% endblock %}

about_me/templates/about_me/tech_dets.html
{% extends "about_me/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">'
    <h3 class="text-center">Technical_Details</h3>
    <p>These series of webpages run on the Django frameworks using <strong><i>functional based views</i></strong>. It is designed as its own app, 'about_me'.<p>

    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h3 class="text-center"> SCRUMBOARD </h3>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>Not Started</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Add photos to landing page</li>
      <li><i class="fa-li fa fa-times"></i>Add text to computer science & cognitive science webpages</li>
      <li><i class="fa-li fa fa-times"></i>Align all columns in class history</li>

    </ul>

    <p></p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>In Progress</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-spinner fa-spin"></i>Nothing ongoing on the about_me webpages: </li>
    </ul>

    <p></p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>Future development goals - "Reach"</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Make each webpage more aesthetically pleasing. Overhaul with alot more css using bootsrap/fontawesome/etc</li>
    </ul>

</div>
</div>


<!-- /Home -->

{% endblock %}