blog/urls.py
from django.urls import path, re_path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog_index',views.blog_index.as_view(),name='blog_index'),

    re_path(r'^about/$',views.AboutView.as_view(),name='about'),

    re_path('r^postList/$',views.PostListView.as_view(),name='post_list'),
    re_path('r^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    re_path('r^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    re_path('r^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    re_path('r^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    re_path('r^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),

    re_path('r^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),

    re_path('r^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),

    re_path('r^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    re_path('r^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),

]

education/urls.py
from django.urls import path
from education import views

app_name = 'education'

urlpatterns = [
    path('education_index',views.education_index,name='education_index'),
    path('comp_sci',views.comp_sci,name='comp_sci'),
    path('cog_sci',views.cog_sci,name='cog_sci'),
    path('class_history',views.class_history,name='class_history'),
    path('tech_dets',views.tech_dets,name='tech_dets'),

]

main_page/urls.py
from django.urls import path
from main_page import views
from data_viz import views as data_viz_views

app_name = 'main_page'

urlpatterns = [
    path('index',views.index,name='index'),
    path('data_viz_index',data_viz_views.data_viz_index,name='data_viz_index'),
]

website/urls.py
from django.contrib import admin
from django.contrib.auth import views

from django.urls import path, re_path, include
from main_page import views
from blog import views as blogViews

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('data_viz/',include('data_viz.urls')),
    path('main_page/',include('main_page.urls')),
    path('education/',include('education.urls')),
    path('about_me/',include('about_me.urls')),
    path('psql_db/',include('psql_db.urls')),

    path('blog/',include('blog.urls')),


    #re_path('accounts/login/$',blogViews.login,name='login'),
    #re_path('accounts/logout/$',blogViews.logout,name='logout',kwargs={'next_page':'/'}),



]

education/models.py
from django.db import models

# Create your models here.

education/views.py
from django.shortcuts import render
# Create your views here.
def education_index(request):
    return render(request, 'education/index.html')

def comp_sci(request):
    return render(request, 'education/comp_sci.html')

def cog_sci(request):
    return render(request, 'education/cog_sci.html')

def class_history(request):
    return render(request, 'education/class_history.html')

def tech_dets(request):
    return render(request, 'education/tech_dets.html')

education/templates/education/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dave-Krieger</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static "main_page/css/style.css" %}"/>

  </head>
  <body>


      <!-- Navbar content -->
      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'main_page:index' %}">Main_Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link text-white" href="{% url 'education:education_index' %}">Education Home</a>
              <a class="nav-item nav-link text-white" href="{% url 'education:comp_sci' %}">Computer Science</a>
              <a class="nav-item nav-link text-white" href="{% url 'education:cog_sci' %}">Cognitive Science</a>
              <a class="nav-item nav-link text-white" href="{% url 'education:class_history' %}">Class History</a>
              <a class="nav-item nav-link text-white" href="{% url 'education:tech_dets' %}">Technical_Details+Scrumboard</a>


          </div>
        </div>
      </nav>
    <div class="">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

education/templates/education/class_history.html
{% extends "education/base.html" %}
{% block body_block %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/hero_img.css' %}">

<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">Wow, that's a lot of classes!</h1>
    <p>I studied at UC Santa Cruz for five consecutive years including the summers in order to accomplish my goals as a double major. At the start, I was originally declared as an engineering student for the first ~3 years. This provided me the opportunity to work with lower level systems and hardware as well as supplying a very strong techinical background. I would have liked to finish out my studies as an engineer, but unfortunately ran out of time.</p>
  </div>
</div>


<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Computer Science - Languages/Algorithms</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">C Programming</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Java</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Compilers</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Data Structures</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Abstract Data Types & Algorithms</th>
          <td>Computer Science</td>
        </tr>

      </tbody>
    </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Computer Science - Applications/Systems</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Computer Networks</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Computer Security</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Operating Systems</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Artificial Intelligence</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Senior Design Project I</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Senior Design Project II</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Senior Design Project III</th>
          <td>Computer Science</td>
        </tr>
      </tbody>
    </table>
</div>


<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Engineering</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Computer Architecture & Assembly (Lower Div)</th>
          <td>Engineering</td>
        </tr>
        <tr>
          <th scope="row">Computer Architecture (Upper div)</th>
          <td>Engineering</td>
        </tr>
        <tr>
          <th scope="row">Electrical Circuits</th>
          <td>Engineering</td>
        </tr>
        <tr>
          <th scope="row">Logic Design</th>
          <td>Engineering</td>
        </tr>
      </tbody>
    </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Human Computer Interaction</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Computer Mediated Communications</th>
          <td>Psychology</td>
        </tr>
        <tr>
          <th scope="row">Social Networks</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Automation</th>
          <td>Engineering</td>
        </tr>
        <tr>
          <th scope="row">Natural Artificial Intelligence</th>
          <td>Psychology</td>
        </tr>
        <tr>
          <th scope="row">Universal Access</th>
          <td>Engineering</td>
        </tr>
        <tr>
          <th scope="row">Engineering Ethics</th>
          <td>Engineering</td>
        </tr>
      </tbody>
    </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
  <h3>Physics</h3>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Class Name</th>
        <th scope="col">Offering Department</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Mechanics</th>
        <td>Physics</td>
      </tr>
      <tr>
        <th scope="row">Waves & Optics</th>
        <td>Physics</td>
      </tr>
      <tr>
        <th scope="row">Electricity & Magnetism</th>
        <td>Physics</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
  <h3>Mathematics</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Differential Calculus</th>
          <td>Math</td>
        </tr>
        <tr>
          <th scope="row">Integral Calculus</th>
          <td>Math</td>
        </tr>
        <tr>
          <th scope="row">Multivariable Calculus</th>
          <td>Math</td>
        </tr>
        <tr>
          <th scope="row">Vector Calculus</th>
          <td>Math</td>
        </tr>
        <tr>
          <th scope="row">Probability/Statistics</th>
          <td>Math</td>
        </tr>
        <tr>
          <th scope="row">Linear Algera</th>
          <td>Math</td>
        </tr>
        <tr>
          <th scope="row">Applied Discrete Mathematics</th>
          <td>Engineering</td>
        </tr>
        <tr>
          <th scope="row">Statistics & Psychology</th>
          <td>Psychology</td>
        </tr>
      </tbody>
    </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Cognitive Science/Psychology</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Cognitive Neuroscience</th>
          <td>Psychology</td>
        </tr>
        <tr>
          <th scope="row">Visual Spatial Cognition</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Fundamental Cognitive Theories</th>
          <td>Psychology</td>
        </tr>
        <tr>
          <th scope="row">Research Methods</th>
          <td>Psychology</td>
        </tr>
        <tr>
          <th scope="row">Psychology of Reading</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Psychology of Language</th>
          <td>Computer Science</td>
        </tr>
        <tr>
          <th scope="row">Feelings and Emotions</th>
          <td>Computer Science</td>
        </tr>
      </tbody>
    </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Writing</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Rhetoric & Inquiry</th>
          <td>Writing</td>
        </tr>
        <tr>
          <th scope="row">Biological Antrhopology</th>
          <td>Antrhopology</td>
        </tr>
        <tr>
          <th scope="row">Environment and Us</th>
          <td>Writing</td>
        </tr>
        <tr>
          <th scope="row">Creative Writing</th>
          <td>Writing</td>
        </tr>
      </tbody>
    </table>
</div>

<div class="container">
  <hr style="width: 100%; color: black; height: 16px; background-color:black;" />
    <h3>Foreign languages</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Class Name</th>
          <th scope="col">Offering Department</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Chinese I</th>
          <td>Linguistics</td>
        </tr>
        <tr>
          <th scope="row">Chinese II</th>
          <td>Linguistics</td>
        </tr>
        <tr>
          <th scope="row">Chinese III</th>
          <td>Linguistics</td>
        </tr>
        <tr>
          <th scope="row">Chinese IV</th>
          <td>Linguistics</td>
        </tr>
      </tbody>
    </table>
</div>

<!-- /Home -->

{% endblock %}

education/templates/education/cog_sci.html
{% extends "education/base.html" %}
{% block body_block %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/hero_img.css' %}">

<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">Cognitive Science</h1>
    <h3>#A page dedicated to cog sci</h3>
  </div>
</div>


<!-- /Home -->

{% endblock %}

education/templates/education/comp_sci.html
{% extends "education/base.html" %}
{% block body_block %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/hero_img.css' %}">

<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">Computer Science</h1>
    <h5>The path for graduation as a computer scientist at UC Santa Cruz is based upon ~five different pillars: </h5>
    <ul>
      <li>Mathematics</li>
      <li>Algorithms</li>
      <li>Data Structures</li>
      <li>Computer Systems</li>
      <li>Variety of Languages</li>


    </ul>
  </div>
</div>

<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">Lower Division Courses</h1>

    <h5>Programming Basics</h5>
    <p>Students take a series of introductory courses covering c & java, data structures, and algorithms. I don't really remember too much about the assignments unfortunately, but here are a few things which still remember about back then</p>
    <ul>
      <li>Create a RPN in C</li>
      <li>Basic data structures in java & C: linked lists, stacks, queues</li>
      <li>Basic algorithms: Insertion, buble, merge, quick, binary</li>
      <li>Basic SSH to unix server</li>
    </ul>

    <p></p>
    <h5>Mathematics</h5>
    <p>Math courses develop students ability to understand computer algorithms, data structures, and systems/applications. I wound taking a long series of mathematics classes originally as a computer engineer where I completed four different calculus courses as well as other fundamental math courses such as linear algebra and statistics. While these courses provided necessary insights towards computer science comprehension, they also served as the backbone of many other classes such as physics, electrical circuits, and AI.</p>

    <p></p>
    <h5>Physics</h5>
    <p>I took a series of three engineering physics classes: mechanics, waves & opics, and electricity & magnetism (E&M). The E&M class was by far the most valuable for its obvious relation towards computers. It helped me ground the connection between computer architecture and 'the real world'. However, the studies in waves & optics was suprisingly helpful for my studies in cognitive science when discussing visual perception. </p>

  </div>
</div>



<div class="container">
  <div class="jumbotron">'
    <h1 class="text-center">Upper Division Courses</h1>

    <p></p>
    <h5>Computer Systems</h5>
    <p  style="text-indent: 40px">The UCSC CS deparment requires students to complete a set of 'fundamental' computer system courses as well as a set of elective courses. Some of the most notable required courses I took were operating systems, computer architecture, and algorithsm/ADTs. These three classes really grew my understanding about the lower-level processes that occur within computers. While I did also take a compiler design class, I feel it didn't really fufill a void in my education. Once I completed it, I though, "<i>Wow, I guess I understand how my code is interpretted. Unless I go into a niche CS field, I doubt I will rely on the information I learned there. </i>". THE ADT & Algorithms class was likely one of the most growthful classes I experienced because I apply what I learned there towards almost everything else I do. </p>
    <p  style="text-indent: 40px">The elective computer system courses helped prepare me 'for the real world'. I took classes for subjects such as computer networks and security which are universally applicable. I particularly enjoyed the security class because we used multiple languages and actually 'attacked' secure servers in order to gain first-hand knowledge about weaknesses. There were alot of cool assignments in that class that I would LOVE to talk about.</p>

    <p></p>
    <h5>Senior Design Project</h5>
    <p style="text-indent: 40px">Every CS/EE student is required to complete a year long 'capstone' project in order to graduate. During this time, students work together in teams of 4-6 members with the support of corporate or factilty sponsorship. The first quarter is dedicated to learning software development practices such as the agile methodology, clean coding, and version control while the second and third quarter has students apply these principles based on the sponsor's project.</p>
    <p style="text-indent: 40px">My capstone project, visualizing climate change, was sponsored through the capstone course instructor, Richard Julig. I led a team of three other students as scrum master to develop the data visualizations featured on this <a href="https://climate-visuals.herokuapp.com/">website</a>. If you would like to learn more about my contributions or learn more about the project click <a href="http://127.0.0.1:8000/data_viz/sdp">here</a>. Ultimately, it taught me alot (both good and bad!) about the development process and how to work as a team.</p>
    <p style="text-indent: 40px"></p>

  </div>
</div>
<!-- /Home -->

{% endblock %}

education/templates/education/index.html
{% extends "education/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">'
    <h1><center>Education</center></h1>
    <p><center>The journey originated with me as an undeclared computer engineer and transformed into my double major as a computer & cognitive scientist. Click around and explore to learn about my experinces within each program.</center></h3>

    <p></p>
    <h5 class="text-center">Table of Contents</h5>

    <div class="list-group">

      <a href="{% url 'education:comp_sci' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Computer Science</h5>
        </div>
        <p class="mb-1">My experience within the computer science program and what I learned/accomplished</p>
        <small class="text-muted">Education/Portfolio</small>
      </a>

      <a href="{% url 'education:cog_sci' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Cognitive Science</h5>
        </div>
        <p class="mb-1">My experience within the cognitive science program and what I learned/accomplished</p>
        <small class="text-muted">Education/Portfolio</small>
      </a>

      <a href="{% url 'education:class_history' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Class History</h5>
        </div>
        <p class="mb-1">An exahustive list of all the classes I have taken. It is sorted based on categories such as:
          <ul>
            <li>Computer Science - Languages/Algorithms</li>
            <li>Computer Science - Applications/Systems</li>
            <li>Human Computer Interaction</li>
            <li>Mathematics</li>
            <li>... etc</li>
          </ul>
        </p>
        <small class="text-muted">Education</small>
      </a>

      <a href="{% url 'education:tech_dets' %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">Technical_Details+Scrumboard</h5>
        </div>
        <p class="mb-1">A brief description how the education webpages were developed and provides a psuedo-scrumboard for my plans</p>
        <small class="text-muted">Personality</small>
      </a>
    </div>
    <p></p>
  </div>
</div>


{% endblock %}

education/templates/education/tech_dets.html
{% extends "education/base.html" %}
{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron">'
    <h3 class="text-center">Technical_Details</h3>
    <p>These series of webpages run on the Django frameworks using <strong><i>functional based views</i></strong>. It is designed as its own app, 'education'.</p>

    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h3 class="text-center"> SCRUMBOARD </h3>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />

    <h5>Not Started</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Add writing to comp sci page</li>
      <li><i class="fa-li fa fa-times"></i>Add writing to cog sci page</li>
      <li><i class="fa-li fa fa-times"></i>Align all columns in class history</li>
    </ul>

    <p></p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>In Progress</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-spinner fa-spin"></i>Nothing ongoing on the education webpages: </li>
    </ul>


    <p></p>
    <hr style="width: 100%; color: black; height: 8px; background-color:black;" />
    <h5>Future development goals - "Reach"</h5>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-times"></i>Make each webpage more aesthetically pleasing. Overhaul with alot more css using bootsrap/fontawesome/etc</li>
      <li><i class="fa-li fa fa-times"></i>Convert my 'class history' webpage from raw HTML to a <strong><i></i>class based view/model.</strong></li>
      <ul class="fa-ul">
        <li><i class="fa-li fa fa-times"></i>Create MVC's for course & category</li>
        <li><i class="fa-li fa fa-times"></i>Save course history & associated categories to database</li>
        <li><i class="fa-li fa fa-times"></i>Convert raw HTML to use new class based models</li>
        <li><i class="fa-li fa fa-times"></i>Create user selection methods to filter/view information as they desire</li>
        <li><i class="fa-li fa fa-times"></i>Attatch href URLS to each class taken to provide more information</li>
      </ul>
    </ul>

</div>
</div>


<!-- /Home -->

{% endblock %}